direction: up
MathOperation: {
  shape: class
}
Addition: {
  type_annotated_field_in_class: 'int'
  not_annotated_field
  __init__(self, numbers): 'None'
  sum_numbers(self): 'int'
  shape: class
}
Addition -> MathOperation
